"""Render the dashboard for hosting somewhere other than the vehicle node.

The interface moved to Home Assistant so the Pi Zero stops rendering a page
for a browser it cannot see and goes back to doing the one thing it is well
placed to do: sit on the OBD port and record. What moves is the *serving*,
not the page -- there is exactly one ``dashboard.html`` in this repository and
this module writes a copy of it with the node's address stamped into the head.

Two copies of an interface is the failure this avoids. They both render, one
of them is wrong, and nothing says which. So the panel is generated rather
than maintained, and regenerating it is the only way to change it.

The stamped page reads the node cross-origin, which the node refuses until it
is started with ``--allow-origin`` naming the Home Assistant origin exactly.
Both ends have to agree before a browser will move a single byte, and neither
end can be talked into a wildcard.
"""

from __future__ import annotations

import argparse
import re
import sys
from importlib.resources import files
from pathlib import Path
from urllib.parse import urlsplit

#: Where the page expects to find the meta tag it reads its API base from.
HEAD_ANCHOR = "<head>"

#: Written into the generated file so nobody edits the wrong copy. The build
#: is one command; a hand edit here is lost the next time it runs.
BANNER = (
    "<!-- GENERATED by `python3 -m hummer_obd.hapanel`. Do not edit.\n"
    "     The source is src/hummer_obd/dashboard.html in the hummer_obdII\n"
    "     repository; this file is that page with the node's address stamped\n"
    "     in. Edit the source and regenerate, or the next build silently\n"
    "     discards whatever was changed here. -->"
)


def _valid_base(base: str) -> bool:
    """Whether *base* is an origin a browser would actually fetch from."""
    parts = urlsplit(base)
    if parts.scheme not in ("http", "https") or not parts.netloc:
        return False
    # A path, query or fragment on the API base would be silently concatenated
    # onto every endpoint and produce nonsense URLs.
    return not parts.path.strip("/") and not parts.query and not parts.fragment


def render(api_base: str, page: str | None = None) -> str:
    """The dashboard, pointed at *api_base* instead of its own origin."""
    base = api_base.rstrip("/")
    if not _valid_base(base):
        raise ValueError(
            f"api base must be scheme://host[:port] with no path, not {api_base!r}")
    source = page if page is not None else (
        files("hummer_obd").joinpath("dashboard.html").read_text(encoding="utf-8"))
    if HEAD_ANCHOR not in source:
        raise ValueError("dashboard.html has no <head> to stamp")
    # Searched inside the head only. The page's own script mentions the tag it
    # reads, and a comment in that script describes it in full -- a whole-file
    # search matched the description and refused to stamp the very page this
    # exists to stamp. A stamp lives in the head, so that is where to look.
    head = source[:source.index("</head>")] if "</head>" in source else source
    if re.search(r'<meta\b[^>]*\bname\s*=\s*([\'"])hummer-api\1', head):
        raise ValueError("this page already carries an api base; refusing to double-stamp")
    # Quoting: the value goes into an HTML attribute, and _valid_base has
    # already refused anything with a path or query, but a host can still
    # contain a quote in a malformed input.
    if '"' in base or "<" in base or ">" in base:
        raise ValueError("api base contains characters that cannot go in an attribute")
    stamp = f'{HEAD_ANCHOR}\n{BANNER}\n<meta name="hummer-api" content="{base}">'
    return _widen_csp(source.replace(HEAD_ANCHOR, stamp, 1), base)


def _widen_csp(source: str, base: str) -> str:
    """Let the page reach the node it was just pointed at, and nothing more.

    The page carries its own Content-Security-Policy, and that policy says
    ``connect-src 'self'`` -- correct when the node serves the page, and fatal
    the moment it is hosted anywhere else: every fetch is blocked, the panel
    renders its empty state, and the only evidence is a console message
    nobody is looking at.

    So the node's origin is added to exactly the two directives that need it,
    and nothing else is relaxed. ``'self'`` stays, because the panel is still
    served by whoever is hosting it.
    """
    match = re.search(
        r'<meta\b[^>]*http-equiv\s*=\s*([\'"])Content-Security-Policy\1[^>]*'
        # The policy is delimited by whichever quote opened it, and it is full
        # of the other one -- 'none', 'unsafe-inline'. A plain [^'"]* stops
        # at the first source expression and matches nothing useful.
        r'content\s*=\s*([\'"])(?P<policy>(?:(?!\2).)*)\2',
        source, re.I)
    if not match:
        raise ValueError("the page has no Content-Security-Policy to widen")
    policy = match.group("policy")
    widened = []
    for directive in policy.split(";"):
        name = directive.strip().split(" ")[0] if directive.strip() else ""
        if name in ("connect-src", "img-src"):
            directive = directive.rstrip() + " " + base
        widened.append(directive)
    updated = ";".join(widened)
    for needed in ("connect-src", "img-src"):
        if needed not in policy:
            raise ValueError(f"the page's policy has no {needed} to widen")
    return source[:match.start("policy")] + updated + source[match.end("policy"):]


def origin_of(api_base: str) -> str:
    """The origin string the node must be told to allow.

    Handed back so the two halves of the arrangement are produced from one
    place: the value stamped into the page, and the value the node has to be
    started with, cannot be typed differently by accident.
    """
    parts = urlsplit(api_base)
    return f"{parts.scheme}://{parts.netloc}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render the dashboard for hosting outside the vehicle node.")
    parser.add_argument("--api", required=True, metavar="URL",
                        help="where the node's API lives, e.g. http://100.71.118.116:8765")
    parser.add_argument("--out", default="-", metavar="PATH",
                        help="file to write, or - for stdout (default)")
    args = parser.parse_args(argv)

    try:
        body = render(args.api)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.out == "-":
        sys.stdout.write(body)
    else:
        target = Path(args.out)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        print(f"wrote {target} ({len(body)} bytes), reading {args.api}", file=sys.stderr)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
